[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
aes-gcm-mini = {path = "../aes-gcm-mini"}
bincode = "1.3.3"
aes-gcm = "0.10.3"